package com.recruitment.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdvertisementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvertisementAllPropertiesEquals(Advertisement expected, Advertisement actual) {
        assertAdvertisementAutoGeneratedPropertiesEquals(expected, actual);
        assertAdvertisementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvertisementAllUpdatablePropertiesEquals(Advertisement expected, Advertisement actual) {
        assertAdvertisementUpdatableFieldsEquals(expected, actual);
        assertAdvertisementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvertisementAutoGeneratedPropertiesEquals(Advertisement expected, Advertisement actual) {
        assertThat(actual)
            .as("Verify Advertisement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvertisementUpdatableFieldsEquals(Advertisement expected, Advertisement actual) {
        assertThat(actual)
            .as("Verify Advertisement relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdvertisementUpdatableRelationshipsEquals(Advertisement expected, Advertisement actual) {
        // empty method
    }
}
