package com.recruitment.backend.domain;

import static com.recruitment.backend.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ApplicationFeeCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationFeeCategoryAllPropertiesEquals(ApplicationFeeCategory expected, ApplicationFeeCategory actual) {
        assertApplicationFeeCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertApplicationFeeCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationFeeCategoryAllUpdatablePropertiesEquals(
        ApplicationFeeCategory expected,
        ApplicationFeeCategory actual
    ) {
        assertApplicationFeeCategoryUpdatableFieldsEquals(expected, actual);
        assertApplicationFeeCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationFeeCategoryAutoGeneratedPropertiesEquals(
        ApplicationFeeCategory expected,
        ApplicationFeeCategory actual
    ) {
        assertThat(actual)
            .as("Verify ApplicationFeeCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationFeeCategoryUpdatableFieldsEquals(ApplicationFeeCategory expected, ApplicationFeeCategory actual) {
        assertThat(actual)
            .as("Verify ApplicationFeeCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getFee()).as("check fee").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFee()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationFeeCategoryUpdatableRelationshipsEquals(
        ApplicationFeeCategory expected,
        ApplicationFeeCategory actual
    ) {
        // empty method
    }
}
