package com.recruitment.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApplicantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicantAllPropertiesEquals(Applicant expected, Applicant actual) {
        assertApplicantAutoGeneratedPropertiesEquals(expected, actual);
        assertApplicantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicantAllUpdatablePropertiesEquals(Applicant expected, Applicant actual) {
        assertApplicantUpdatableFieldsEquals(expected, actual);
        assertApplicantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicantAutoGeneratedPropertiesEquals(Applicant expected, Applicant actual) {
        assertThat(actual)
            .as("Verify Applicant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicantUpdatableFieldsEquals(Applicant expected, Applicant actual) {
        assertThat(actual)
            .as("Verify Applicant relevant properties")
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPasswordHash()).as("check passwordHash").isEqualTo(expected.getPasswordHash()))
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getIsAccountActivated()).as("check isAccountActivated").isEqualTo(expected.getIsAccountActivated())
            )
            .satisfies(a -> assertThat(a.getAuthorities()).as("check authorities").isEqualTo(expected.getAuthorities()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicantUpdatableRelationshipsEquals(Applicant expected, Applicant actual) {
        // empty method
    }
}
