package com.recruitment.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigAllPropertiesEquals(Config expected, Config actual) {
        assertConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigAllUpdatablePropertiesEquals(Config expected, Config actual) {
        assertConfigUpdatableFieldsEquals(expected, actual);
        assertConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigAutoGeneratedPropertiesEquals(Config expected, Config actual) {
        assertThat(actual)
            .as("Verify Config auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigUpdatableFieldsEquals(Config expected, Config actual) {
        assertThat(actual)
            .as("Verify Config relevant properties")
            .satisfies(a -> assertThat(a.getPortalActive()).as("check portalActive").isEqualTo(expected.getPortalActive()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getSampleFormUrl()).as("check sampleFormUrl").isEqualTo(expected.getSampleFormUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConfigUpdatableRelationshipsEquals(Config expected, Config actual) {
        // empty method
    }
}
